#!/usr/bin/env python3
"""Check the actual public file inventory, metadata, assets, links and generated bytes."""
from pathlib import Path
import hashlib
import json
import re
import subprocess
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
ATTRIBUTION = ("This theme is based on the outstanding Cupertino theme created by Alexis C. "
               "Cupertino provides much of the visual foundation and native-feeling interface that made this project possible. "
               "This project extends that foundation with a different focus: long-form reading and document consumption in Obsidian.")


def check_notices():
    css = (ROOT / "theme.css").read_text()
    license_text = (ROOT / "LICENSE").read_text()
    current = json.loads((ROOT / "CURRENT.json").read_text())
    font_license = Path("updates") / current["version"] / "fonts/upstream/OFL.txt"
    for relative in [Path("licenses/Reading-Lab-MIT.txt"), Path("licenses/Minimal-MIT.txt"),
                     Path("licenses/Lucide-LICENSE.txt"), font_license]:
        notice = (ROOT / relative).read_text().strip()
        assert notice in css and notice in license_text, f"Incomplete distributed notice: {relative}"
    upstream = (ROOT / "licenses/Cupertino-MIT.txt").read_text().strip()
    permission = upstream[upstream.index("Permission is hereby granted"):]
    for text in [css, license_text]:
        assert permission in text, "Cupertino permission/disclaimer text was changed"
        for line in upstream.splitlines():
            if line.startswith("Copyright"):
                assert line in text, "Cupertino copyright notice was removed"
    for relative in ["README.md", "docs/CUPERTINO-AUTHOR-OUTREACH.md"]:
        assert ATTRIBUTION in (ROOT / relative).read_text(), f"Missing required attribution: {relative}"
    for relative in ["UPSTREAM.md", "THIRD_PARTY_NOTICES.md", "docs/AUTHOR-REVIEW-READINESS.md"]:
        assert (ROOT / relative).is_file(), f"Missing review document: {relative}"


def public_files():
    result = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
                            cwd=ROOT, check=True, capture_output=True)
    return sorted({Path(p.decode()) for p in result.stdout.split(b"\0") if p})


def main():
    current = json.loads((ROOT / "CURRENT.json").read_text())
    build = json.loads((ROOT / current["build"]).read_text())
    manifest = json.loads((ROOT / "manifest.json").read_text())
    package = json.loads((ROOT / "package.json").read_text())
    versions = json.loads((ROOT / "versions.json").read_text())
    assert all(isinstance(manifest.get(key), str) and manifest[key].strip()
               for key in ["name", "author", "version", "minAppVersion"]), "Incomplete theme manifest"
    assert re.fullmatch(r"\d+\.\d+\.\d+", manifest["version"])
    assert manifest["version"] == current["version"] == package["version"] == build["version"]
    assert manifest["name"] == current["name"] == build["name"]
    assert versions[manifest["version"]] == manifest["minAppVersion"] == build["minAppVersion"]
    assert all(re.fullmatch(r"\d+\.\d+\.\d+", key) and isinstance(value, str)
               and re.fullmatch(r"\d+\.\d+\.\d+", value) for key, value in versions.items()), "Invalid compatibility history"
    for name in ["theme.css", "manifest.json", "LICENSE"]:
        content = (ROOT / name).read_bytes()
        assert content == (ROOT / build["folder"] / name).read_bytes(), f"Stale public {name}"
        assert hashlib.sha256(content).hexdigest() == build["files"][name]
    check_notices()
    files = public_files()
    forbidden = {".obsidian", ".codex", ".agents", ".venv", "node_modules", "work", "reports", "evidence", "__pycache__", ".DS_Store"}
    local_path = re.compile("/" + r"(?:Users|private/var|var/folders)/")
    secret = re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{30,}|sk-[A-Za-z0-9]{30,})\b")
    links = 0
    for relative in files:
        p = ROOT / relative
        assert not forbidden.intersection(relative.parts), f"Private artifact in public inventory: {relative}"
        assert not p.is_symlink(), f"Public symlink: {relative}"
        assert not p.name.startswith((".env", "._")), f"Local configuration: {relative}"
        if p.suffix in {".woff2", ".ttf", ".png", ".jpg"}:
            continue
        text = p.read_text()
        assert not local_path.search(text), f"Machine-specific path: {relative}"
        assert not secret.search(text), f"Credential-shaped string: {relative}"
        assert not re.search(r"^(?:<{7}|={7}|>{7})(?: |$)", text, re.M), f"Conflict marker: {relative}"
        if p.suffix == ".json":
            json.loads(text)
        if p.suffix == ".md" and relative.parts[0] != "design":
            for link in re.findall(r"\]\(([^)]+)\)", text):
                target = link.split("#", 1)[0]
                if not target or re.match(r"^[a-z]+:", target):
                    continue
                assert (p.parent / unquote(target)).exists(), f"Broken local link: {relative}: {link}"
                links += 1
    subprocess.run(["node", "scripts/check-assets.cjs"], check=True, cwd=ROOT)
    print(json.dumps({"status": "PASS", "publicFiles": len(files), "localLinks": links,
                      "version": manifest["version"], "cssSha256": build["cssSha256"]}))


if __name__ == "__main__":
    main()
