#!/usr/bin/env python3
"""Build the current theme offline from owned CSS and pinned static fonts."""
from pathlib import Path
import argparse
import base64
import hashlib
import json

ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parents[1]
NAME = "Cupertino Reading Lab v4"
VERSION = "0.4.5"
MIN_APP = "1.13.4"


def sha(data):
    return hashlib.sha256(data).hexdigest()


def make_payload():
    theme_license = (PROJECT / "licenses/Reading-Lab-MIT.txt").read_text().strip()
    assert "MIT License" in theme_license and "*/" not in theme_license
    inherited_notices = "\n\n".join((PROJECT / "licenses" / name).read_text().strip() for name in ["Minimal-MIT.txt", "Lucide-LICENSE.txt"])
    theme_license += "\n\nAdditional inherited components\n\n" + inherited_notices
    fonts = json.loads((ROOT / "fonts/PROVENANCE.json").read_text())
    assert fonts["family"] == "Cupertino Newsreader" and len(fonts["faces"]) == 8
    license_text = (ROOT / "fonts/upstream/OFL.txt").read_text().strip()
    assert "SIL OPEN FONT LICENSE Version 1.1" in license_text and "*/" not in license_text
    font_css = "/* Embedded Newsreader: static optical size 24; no runtime variation axes.\n" + license_text + "\n*/\n"
    for face in fonts["faces"]:
        data = (ROOT / "fonts" / face["file"]).read_bytes()
        assert sha(data) == face["sha256"] and data[:4] == b"wOF2"
        encoded = base64.b64encode(data).decode("ascii")
        font_css += (
            '\n@font-face {\n  font-family: "Cupertino Newsreader";\n'
            f'  font-style: {face["style"]};\n  font-weight: {face["weight"]};\n'
            '  font-display: swap;\n'
            f'  src: url("data:font/woff2;base64,{encoded}") format("woff2");\n}}\n'
        )
    css = ("/*\n" + theme_license + "\n*/\n\n" +
           (ROOT / "source/base.css").read_text().rstrip() + "\n\n" + font_css + "\n" +
           (ROOT / "source/reader-font.css").read_text() + "\n" +
           (ROOT / "source/keyboard-focus.css").read_text() + "\n" +
           (ROOT / "source/settings-layout.css").read_text() + "\n" +
           (ROOT / "source/wide-content.css").read_text()).encode()
    manifest = {"name": NAME, "version": VERSION, "minAppVersion": MIN_APP,
                "author": "Logan Juhl; Cupertino by Alexis C; Newsreader by Production Type"}
    readme = f"""# {NAME}

Version {VERSION}. A quiet reading theme with Newsreader included for offline use.

Copy this folder to your vault's `.obsidian/themes/` folder, then select **{NAME}**
in Appearance. Leave **Text font** at its default to use bundled Newsreader.
An explicit Text font preference still overrides the theme. Use the default
monospace font or Menlo for code. No font installation or plugin is required.

The eight static WOFF2 faces cover regular, medium, semibold and bold, with matching
italics. They preserve all 564 upstream Unicode mappings and use fixed optical size
24. Unsupported characters use the platform fallback. Interface typography follows
your app preference. Font size follows Appearance.

V4's light/dark paper and ink, reading hierarchy, callout colors, tables and native
scrolling are retained. This release also normalizes CSS, removes a dead focus
selector, restores a visible keyboard-focus ring on settings switches, and keeps
settings dropdown labels readable when a new settings window opens. On phones,
settings controls wrap to keep the theme selector and Manage button on-screen.
Edge-to-edge table, image and Bases helpers account for the native scrollbar.
Long display equations scroll locally without widening the surrounding note.
Minimum Obsidian: {MIN_APP}.
Actual tested runtimes and limits are recorded in the release validation report;
the minimum app version does not imply every installer or operating system was tested.

This is a derivative of Cupertino by Alexis C (MIT), with inherited Minimal
helpers and Lucide icons credited in LICENSE. Newsreader by Production Type is
licensed under SIL OFL 1.1. The notices are in LICENSE and inside theme.css so
they travel with an installed community theme.

For rollback, restore the saved prior theme folder or choose the previous theme
in Appearance. This installer contains no vault, personal data, or executable code.
"""
    return {"theme.css": css, "manifest.json": (json.dumps(manifest, indent=2)+"\n").encode(),
            "README.md": readme.encode(), "LICENSE": (theme_license+"\n\nNewsreader font software\n\n"+license_text+"\n").encode()}, fonts


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Compare current generated bytes without writing")
    args = parser.parse_args()
    payload, fonts = make_payload()
    folder = ROOT / "theme" / NAME
    if args.check:
        assert {p.name for p in folder.iterdir()} == set(payload)
        for name, content in payload.items():
            assert (folder / name).read_bytes() == content, f"Stale generated {name}"
        print(json.dumps({"status": "PASS", "files": len(payload), "cssSha256": sha(payload["theme.css"])}))
        return
    folder.mkdir(parents=True, exist_ok=True)
    assert not folder.is_symlink()
    assert {p.name for p in folder.iterdir()} <= set(payload)
    for name, content in payload.items():
        destination = folder / name
        assert not destination.is_symlink()
        destination.write_bytes(content)
    inputs = {p.relative_to(PROJECT).as_posix(): sha(p.read_bytes()) for p in [ROOT/"build.py", *sorted((ROOT/"source").glob("*.css")), ROOT/"fonts/PROVENANCE.json", ROOT/"fonts/upstream/OFL.txt", *sorted((PROJECT/"licenses").glob("*.txt"))]}
    record = {"name": NAME, "version": VERSION, "minAppVersion": MIN_APP,
              "folder": folder.relative_to(PROJECT).as_posix(), "cssSha256": sha(payload["theme.css"]),
              "cssBytes": len(payload["theme.css"]), "sourceHashes": inputs,
              "fontFaces": fonts["faces"], "files": {name: sha(content) for name, content in payload.items()}}
    (ROOT/"BUILD.json").write_text(json.dumps(record, indent=2)+"\n")
    print(json.dumps({"version": VERSION, "cssBytes": record["cssBytes"], "cssSha256": record["cssSha256"], "fontFaces": 8}))


if __name__ == "__main__":
    main()
