/* Test the actual installed current theme's CSS fonts; never inject FontFace assets. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),qa=require('../../scripts/config.cjs');
const build=JSON.parse(fs.readFileSync(path.join(__dirname,'BUILD.json')));
const family='Cupertino Newsreader',stage=qa.final,out=path.join(__dirname,'evidence/fonts');
assert.equal(stage.css_sha256,build.cssSha256);fs.mkdirSync(out,{recursive:true});
const result={status:'INCOMPLETE',scope:'Exact release CSS in isolated macOS Obsidian. Phone geometries use desktop emulation; physical-device evidence is separate.',startedAt:new Date().toISOString(),cssSha256:stage.css_sha256,scriptSha256:qa.hashFile(__filename),family,cases:[],reloads:[],faceGlyphs:[],errors:[],remoteFontRequests:[]};
const save=()=>fs.writeFileSync(path.join(out,'RESULTS.json'),JSON.stringify(result,null,2)+'\n');save();
async function loadFaces(page){await page.evaluate(async({family,faces})=>{for(const f of faces)await document.fonts.load(`${f.style} ${f.weight} 23px "${family}"`);await document.fonts.ready},{family,faces:build.fontFaces});}
async function platformFonts(page,selector){const session=await page.context().newCDPSession(page);try{await session.send('DOM.enable');await session.send('CSS.enable');const doc=await session.send('DOM.getDocument');const node=await session.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector});assert(node.nodeId,selector);return(await session.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId})).fonts;}finally{await session.detach()}}
(async()=>{const browser=await chromium.connectOverCDP(qa.endpoint);try{
 const page=browser.contexts()[0].pages().find(p=>p.url().includes('index.html'));await qa.guard(page,result);
 page.on('request',r=>{if(r.resourceType()==='font'&&/^https?:/.test(r.url()))result.remoteFontRequests.push(r.url())});
 await qa.selectTheme(page,stage);
 // Natural first-use loading: no document.fonts.load calls and no FontFace injection.
 // Persist the real theme default before the reload so the startup does not use
 // the explicit system/QA font preference left by an earlier regression suite.
 const startupFile='QA Font Startup.md';
 const sentence='A quiet reading surface gives each word time to settle. Café, Việt Nam and “curly quotes” keep their shape while the reader moves through a long page. ';
 fs.writeFileSync(path.join(qa.vault,startupFile),'# Newsreader first use\n\n'+build.fontFaces.map((f,i)=>`## Face ${i+1}\n\n`+Array.from({length:6},()=>`<p style="font-weight:${f.weight};font-style:${f.style}">${sentence.repeat(4)}</p>\n`).join('\n')).join('\n'));
 await page.waitForTimeout(200);await page.evaluate(async file=>app.workspace.getLeaf().setViewState({type:'markdown',state:{file,mode:'preview'}}),startupFile);
 await qa.stabilizeTone(page,'dark',stage,{textFontFamily:'',interfaceFontFamily:'',monospaceFontFamily:'Menlo',baseFontSize:23,showInlineTitle:false,readableLineLength:true});
 await page.addInitScript(({family})=>{window.__readerStartup={events:[],errors:[]};for(const type of ['loading','loadingdone','loadingerror'])document.fonts.addEventListener(type,event=>{const faces=[...(event.fontfaces||[])].filter(f=>f.family.includes(family)).map(f=>({weight:f.weight,style:f.style,status:f.status}));window.__readerStartup.events.push({type,time:performance.now(),faces});if(type==='loadingerror'&&faces.length)window.__readerStartup.errors.push(faces)});},{family});
 await page.reload();await page.waitForFunction(()=>typeof app!=='undefined'&&app.workspace?.layoutReady);await qa.guard(page,{});
 await page.waitForFunction(file=>app.workspace.activeLeaf?.view?.file?.path===file,startupFile);
 result.naturalStartupTone=await qa.assertTone(page,'dark',stage);
 await page.waitForFunction(()=>document.fonts.status==='loaded');
 const startupScrolls=[];
 for(const fraction of [0,.12,.25,.38,.51,.64,.77,.9,1,0]){await page.evaluate(f=>{const s=document.querySelector('.markdown-reading-view > .markdown-preview-view');s.scrollTop=(s.scrollHeight-s.clientHeight)*f},fraction);await page.waitForTimeout(200);await page.waitForFunction(()=>document.fonts.status==='loaded');startupScrolls.push(await page.evaluate(()=>{const s=document.querySelector('.markdown-reading-view > .markdown-preview-view');return{top:s.scrollTop,status:document.fonts.status,visible:[...s.querySelectorAll('p,h1,h2')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.bottom>80&&r.top<innerHeight-40}).length}}));}
 assert(startupScrolls.every(s=>s.status==='loaded'&&s.visible>0));
 const eventCount=await page.evaluate(()=>window.__readerStartup.events.length);await page.waitForTimeout(1200);
 result.naturalStartup=await page.evaluate(()=>({...window.__readerStartup,status:document.fonts.status}));result.naturalStartup.scrolls=startupScrolls;result.naturalStartup.quietTailMs=1200;
 assert.equal(result.naturalStartup.errors.length,0);assert.equal(result.naturalStartup.status,'loaded');assert.equal(result.naturalStartup.events.length,eventCount,'Font loading continued after first-use scrolling settled');save();
 for(const [geometry,width,height,mobile]of [['desktop',1280,900,false],['portrait',390,844,true],['landscape',844,390,true]])for(const tone of ['light','dark'])for(const mode of ['reading','live','source']){
  if(await page.evaluate(()=>app.isMobile)!==mobile){await Promise.all([page.waitForEvent('domcontentloaded'),page.evaluate(m=>app.emulateMobile(m),mobile)]);await page.waitForFunction(()=>typeof app!=='undefined'&&app.workspace?.layoutReady);await qa.guard(page,{});}
  await page.setViewportSize({width,height});
  await page.evaluate(async({file,mode})=>{document.querySelector('#qa-text-spacing')?.remove();app.workspace.leftSplit?.collapse();app.workspace.rightSplit?.collapse();for(const leaf of app.workspace.getLeavesOfType('markdown').slice(1))leaf.detach();await app.workspace.getLeaf().setViewState({type:'markdown',state:{file,mode:mode==='reading'?'preview':'source',source:mode==='source'}});},{file:qa.surfaceFile,mode});
  await qa.selectTheme(page,stage);const toneState=await qa.stabilizeTone(page,tone,stage,{textFontFamily:'',interfaceFontFamily:'',monospaceFontFamily:'Menlo',baseFontSize:23,showInlineTitle:false,readableLineLength:true});await loadFaces(page);
  const computed=await page.evaluate(({family,mode})=>{const visible=e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0};const root=[...document.querySelectorAll('.markdown-reading-view > .markdown-preview-view,.markdown-source-view > .cm-editor > .cm-scroller')].find(visible);root.scrollTop=0;const e=root.querySelector(mode==='reading'?'p':'.cm-line');const code=root.querySelector('code');return{font:getComputedStyle(e).fontFamily,codeFont:code?getComputedStyle(code).fontFamily:null,faces:[...document.fonts].filter(f=>f.family.includes(family)).map(f=>({family:f.family,weight:f.weight,style:f.style,status:f.status})),fontStatus:document.fonts.status,overflow:document.documentElement.scrollWidth-innerWidth};},{family,mode});
  assert(computed.font.includes(family));assert.equal(computed.fontStatus,'loaded');assert.equal(computed.faces.length,8);assert(computed.faces.every(f=>f.status==='loaded'));assert(computed.overflow<=1);if(computed.codeFont)assert(computed.codeFont.startsWith('Menlo'));
  const glyphs=await platformFonts(page,mode==='reading'?'.markdown-reading-view > .markdown-preview-view p':'.markdown-source-view .cm-line');assert(glyphs.some(f=>f.isCustomFont&&f.familyName===family&&f.glyphCount>0));
  const file=`${geometry}-${tone}-${mode}.png`;await qa.screenshot(page,{path:path.join(out,file)},tone,stage);
  await page.evaluate(()=>{const m={fontLoads:0,styleWrites:0,style:app.customCss.styleEl};m.listener=()=>m.fontLoads++;m.observer=new MutationObserver(()=>m.styleWrites++);m.observer.observe(m.style,{childList:true,subtree:true,characterData:true});document.fonts.addEventListener('loading',m.listener);window.__readerMonitor=m});
  const scrolls=[];for(const fraction of [0,.2,.85,.1,.95,0]){await page.evaluate(f=>{const s=[...document.querySelectorAll('.markdown-reading-view > .markdown-preview-view,.markdown-source-view > .cm-editor > .cm-scroller')].find(e=>e.clientHeight>0);s.scrollTop=(s.scrollHeight-s.clientHeight)*f},fraction);await page.waitForTimeout(150);const sample=await page.evaluate(()=>{const s=[...document.querySelectorAll('.markdown-reading-view > .markdown-preview-view,.markdown-source-view > .cm-editor > .cm-scroller')].find(e=>e.clientHeight>0);return{top:s.scrollTop,status:document.fonts.status,overflow:document.documentElement.scrollWidth-innerWidth,visibleText:[...s.querySelectorAll('p,h1,h2,h3,h4,h5,h6,li,td,th,pre,.callout-title-inner,.cm-line')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.bottom>70&&r.top<innerHeight-40}).length}});result.activeCase={geometry,tone,mode,fraction,sample};save();assert.equal(sample.status,'loaded');assert(sample.overflow<=1&&sample.visibleText>0);scrolls.push(sample)}
  const monitor=await page.evaluate(()=>{const m=window.__readerMonitor;m.observer.disconnect();document.fonts.removeEventListener('loading',m.listener);return{fontLoads:m.fontLoads,styleWrites:m.styleWrites,replaced:m.style!==app.customCss.styleEl}});assert.deepEqual(monitor,{fontLoads:0,styleWrites:0,replaced:false});
  result.cases.push({geometry,tone,mode,toneState,toneAfter:await qa.assertTone(page,tone,stage),computed,glyphs,scrolls,monitor,screenshot:file,screenshotSha256:qa.hashFile(path.join(out,file))});save();console.log(JSON.stringify({geometry,tone,mode,status:'PASS'}));
 }
 const file='QA Reader Faces.md';const content='# Reader font faces\n\n'+build.fontFaces.map((f,i)=>`<p id="reader-face-${i}" style="font-weight:${f.weight};font-style:${f.style}">Newsreader ${f.weight} ${f.style}: Café, naïve, Straße, Việt Nam. “A quiet place.”</p>\n`).join('\n');
 fs.writeFileSync(path.join(qa.vault,file),content);await page.waitForTimeout(200);
 await page.evaluate(async file=>app.workspace.getLeaf().setViewState({type:'markdown',state:{file,mode:'preview'}}),file);await qa.stabilizeTone(page,'light',stage,{textFontFamily:'',monospaceFontFamily:'Menlo',baseFontSize:23});await loadFaces(page);
 for(let i=0;i<build.fontFaces.length;i++){const f=build.fontFaces[i],fonts=await platformFonts(page,`#reader-face-${i}`);const expected=f.file.replace('.woff2','');assert(fonts.some(font=>font.isCustomFont&&font.postScriptName===expected&&font.glyphCount>0),`Wrong/synthetic face: ${expected}`);result.faceGlyphs.push({weight:f.weight,style:f.style,expected,fonts});save();}
 for(let i=0;i<3;i++){await page.reload();await page.waitForFunction(()=>typeof app!=='undefined'&&app.workspace?.layoutReady);await qa.guard(page,{});await qa.selectTheme(page,stage);await page.evaluate(async()=>app.workspace.getLeaf().setViewState({type:'markdown',state:{file:'QA Long.md',mode:'preview'}}));await qa.stabilizeTone(page,'dark',stage,{textFontFamily:'',monospaceFontFamily:'Menlo',baseFontSize:23});await loadFaces(page);const state=await page.evaluate(()=>({font:getComputedStyle(document.querySelector('.markdown-reading-view p')).fontFamily,status:document.fonts.status}));assert(state.font.includes(family)&&state.status==='loaded');result.reloads.push({iteration:i,...state});save();}
 await qa.stabilizeTone(page,'dark',stage,{textFontFamily:'Georgia',monospaceFontFamily:'Menlo',baseFontSize:23});result.override=await page.evaluate(()=>getComputedStyle(document.querySelector('.markdown-reading-view p')).fontFamily);assert(result.override.startsWith('Georgia'));
 await qa.stabilizeTone(page,'dark',stage,{textFontFamily:'',interfaceFontFamily:'',monospaceFontFamily:'Menlo',baseFontSize:18,autoFullScreen:false,floatingNavigation:false});
 assert.equal(result.cases.length,18);assert.equal(result.faceGlyphs.length,8);assert.equal(result.remoteFontRequests.length,0);delete result.activeCase;result.status='PASS';result.finishedAt=new Date().toISOString();save();
}finally{await browser.close()}})().catch(error=>{result.status='FAIL';result.errors.push(String(error.stack));save();console.error(error);process.exitCode=1});
